sudo: false

language: node_js

node_js: "14"

addons:
  artifacts:
    paths:
    - ./coverage/lcov-report
    - ./coverage/jest-result.txt

cache:
  directories:
  - node_modules

before_install:
- npm update

install:
- npm install

script:
- npm -s run test:coveralls