sudo: false

language: node_js

node_js: "14"

addons:
  artifacts:
    paths:
    - ./coverage/lcov-report

cache:
  directories:
  - node_modules

before_install:
- npm update

install:
- npm install

script:
- npm run test:coveralls